[workspace]
resolver = "2"
members = [
    "audio-player",
    "cli",
    "gui-iced",
]

[workspace.dependencies]
clap = { version = "4.5.16", features = ["derive"] }
thiserror = "1.0.63"
tracing = "0.1.40"