[workspace]
resolver = "2"
members = [
    "audio-player",
    "cli",
    "gui-iced",
    "tui",
]

[workspace.dependencies]
clap = { version = "4.5.16", features = ["derive"] }
color-eyre = { version = "0.6.3" }
thiserror = "1.0.63"
tracing = "0.1.40"
