[package]
name = "ap"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-player = { path = "../audio-player" }
clap = { workspace = true }
color-eyre = { workspace = true }
indicatif = { version = "0.17.8" }
